### ISSUE TITLE
wkwkwkwkwkwkwk

### ISSUE THREAD

**Issue by heliosnarcissus** [arelguatno/AppDev2018#1]
Please make Karina guide. wkwkwkwk :dagger:

**Comment by arelguatno** [comment]
Please use discord or forum for questions. Thanks

**Comment by arelguatno** [comment]
xD

**Comment by heliosnarcissus** [comment]
hahahahaha. How to be Mythic Player in MOBA guide please :dancer:

**Comment by arelguatno** [comment]
Here's the guide http://youjizz.com
